In [19]:
import numpy as np
import pandas as pd
import plotly
from plotly import graph_objs as go
from plotly import plotly as py
from plotly import tools
plotly.tools.set_credentials_file(username="xuexianli", api_key="Q8rr7xPeaOU98CaBbAPV")

## Data explore

In [6]:
NYSE_price = pd.read_csv("prices.csv")

In [7]:
NYSE_price.head(50)

,date,symbol,open,close,low,high,volume
0,2016-01-05 00:00:00,WLTW,123.430000,125.839996,122.309998,126.250000,2163600.0
1,2016-01-06 00:00:00,WLTW,125.239998,119.980003,119.940002,125.540001,2386400.0
2,2016-01-07 00:00:00,WLTW,116.379997,114.949997,114.930000,119.739998,2489500.0
3,2016-01-08 00:00:00,WLTW,115.480003,116.620003,113.500000,117.440002,2006300.0
4,2016-01-11 00:00:00,WLTW,117.010002,114.970001,114.089996,117.330002,1408600.0
5,2016-01-12 00:00:00,WLTW,115.510002,115.550003,114.500000,116.059998,1098000.0
6,2016-01-13 00:00:00,WLTW,116.459999,112.849998,112.589996,117.070000,949600.0
7,2016-01-14 00:00:00,WLTW,113.510002,114.379997,110.050003,115.029999,785300.0
8,2016-01-15 00:00:00,WLTW,113.330002,112.529999,111.919998,114.879997,1093700.0
9,2016-01-19 00:00:00,WLTW,113.660004,110.379997,109.870003,115.870003,1523500.0
10,2016-01-20 00:00:00,WLTW,109.059998,109.300003,108.320000,111.599998,1653900.0
11,2016-01-21 00:00:00,WLTW,109.730003,110.000000,108.320000,110.580002,944300.0
12,2016-01-22 00:00:00,WLTW,111.879997,111.949997,110.190002,112.949997,744900.0
13,2016-01-25 00:00:00,WLTW,111.320000,110.120003,110.000000,114.629997,703800.0
14,2016-01-26 00:00:00,WLTW,110.419998,111.000000,107.300003,111.400002,563100.0
15,2016-01-27 00:00:00,WLTW,110.769997,110.709999,109.019997,112.570000,896100.0
16,2016-01-28 00:00:00,WLTW,110.900002,112.580002,109.900002,112.970001,680400.0
17,2016-01-29 00:00:00,WLTW,113.349998,114.470001,111.669998,114.589996,749900.0
18,2016-02-01 00:00:00,WLTW,114.000000,114.500000,112.900002,114.849998,574200.0
19,2016-02-02 00:00:00,WLTW,113.250000,110.559998,109.750000,113.860001,694800.0
20,2016-02-03 00:00:00,WLTW,113.379997,114.050003,109.639999,114.639999,896300.0
21,2016-02-04 00:00:00,WLTW,114.080002,115.709999,114.080002,116.320000,956300.0
22,2016-02-05 00:00:00,WLTW,115.120003,114.019997,109.709999,116.489998,997100.0
23,2016-02-08 00:00:00,WLTW,113.300003,111.160004,110.459999,113.300003,1200500.0
24,2016-02-09 00:00:00,WLTW,111.169998,110.650002,109.639999,112.110001,1725200.0
25,2016-02-10 00:00:00,WLTW,106.730003,107.519997,106.360001,112.110001,1946000.0
26,2016-02-11 00:00:00,WLTW,105.629997,107.129997,104.110001,109.260002,1319500.0
27,2016-02-12 00:00:00,WLTW,108.559998,107.839996,107.070000,109.430000,922400.0
28,2016-02-16 00:00:00,WLTW,109.110001,110.769997,107.010002,111.300003,1185100.0
29,2016-02-17 00:00:00,WLTW,110.830002,111.239998,107.970001,112.110001,921500.0
30,2016-02-18 00:00:00,WLTW,111.120003,111.599998,108.930000,112.199997,440900.0
31,2016-02-19 00:00:00,WLTW,111.370003,110.330002,107.279999,112.400002,1244300.0
32,2016-02-22 00:00:00,WLTW,111.360001,113.040001,111.010002,113.230003,681300.0
33,2016-02-23 00:00:00,WLTW,112.370003,111.889999,111.349998,112.800003,411200.0
34,2016-02-24 00:00:00,WLTW,110.769997,111.559998,109.820000,112.489998,447300.0
35,2016-02-25 00:00:00,WLTW,111.599998,112.879997,110.750000,112.989998,559200.0
36,2016-02-26 00:00:00,WLTW,113.339996,112.750000,111.010002,114.180000,459900.0
37,2016-02-29 00:00:00,WLTW,113.040001,113.320000,111.650002,115.360001,971600.0
38,2016-03-01 00:00:00,WLTW,114.269997,115.510002,112.650002,115.570000,694100.0
39,2016-03-02 00:00:00,WLTW,115.349998,116.779999,115.199997,117.089996,1159600.0
40,2016-03-03 00:00:00,WLTW,116.489998,117.000000,115.419998,117.669998,884700.0
41,2016-03-04 00:00:00,WLTW,116.610001,117.190002,115.570000,117.480003,692000.0
42,2016-03-07 00:00:00,WLTW,116.050003,116.949997,115.989998,117.480003,898000.0
43,2016-03-08 00:00:00,WLTW,116.500000,116.709999,115.449997,117.370003,844500.0
44,2016-03-09 00:00:00,WLTW,117.050003,116.489998,115.500000,117.309998,796500.0
45,2016-03-10 00:00:00,WLTW,116.910004,116.820000,114.139999,118.000000,416800.0
46,2016-03-11 00:00:00,WLTW,117.930000,120.620003,116.629997,120.760002,590200.0
47,2016-03-14 00:00:00,WLTW,120.419998,120.629997,118.599998,121.040001,495100.0
48,2016-03-15 00:00:00,WLTW,119.839996,120.699997,118.089996,120.760002,515800.0
49,2016-03-16 00:00:00,WLTW,120.349998,120.820000,119.010002,121.040001,562100.0

In [8]:
NYSE_price.tail(10)

,date,symbol,open,close,low,high,volume
851254,2016-12-30,XRAY,58.290001,57.730000,57.540001,58.360001,949200.0
851255,2016-12-30,XRX,8.720000,8.730000,8.700000,8.800000,11250400.0
851256,2016-12-30,XYL,49.980000,49.520000,49.360001,50.000000,646200.0
851257,2016-12-30,YHOO,38.720001,38.669998,38.430000,39.000000,6431600.0
851258,2016-12-30,YUM,63.930000,63.330002,63.160000,63.939999,1887100.0
851259,2016-12-30,ZBH,103.309998,103.199997,102.849998,103.930000,973800.0
851260,2016-12-30,ZION,43.070000,43.040001,42.689999,43.310001,1938100.0
851261,2016-12-30,ZTS,53.639999,53.529999,53.270000,53.740002,1701200.0
851262,2016-12-30 00:00:00,AIV,44.730000,45.450001,44.410000,45.590000,1380900.0
851263,2016-12-30 00:00:00,FTV,54.200001,53.630001,53.389999,54.480000,705100.0

Key: date, symbol

Value: open, close, low, high, volume

From the head of the file, the date is unqiue, but from the tail we noticed that we need the combination of date and symbol is unqiue. So the keys of this dataset are date column and symbol column. Other columns are quantitative value, so they are not the keys.

In [9]:
set(NYSE_price["symbol"])

{'A',
 'AAL',
 'AAP',
 'AAPL',
 'ABBV',
 'ABC',
 'ABT',
 'ACN',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADS',
 'ADSK',
 'AEE',
 'AEP',
 'AES',
 'AET',
 'AFL',
 'AGN',
 'AIG',
 'AIV',
 'AIZ',
 'AJG',
 'AKAM',
 'ALB',
 'ALK',
 'ALL',
 'ALLE',
 'ALXN',
 'AMAT',
 'AME',
 'AMG',
 'AMGN',
 'AMP',
 'AMT',
 'AMZN',
 'AN',
 'ANTM',
 'AON',
 'APA',
 'APC',
 'APD',
 'APH',
 'ARNC',
 'ATVI',
 'AVB',
 'AVGO',
 'AVY',
 'AWK',
 'AXP',
 'AYI',
 'AZO',
 'BA',
 'BAC',
 'BAX',
 'BBBY',
 'BBT',
 'BBY',
 'BCR',
 'BDX',
 'BEN',
 'BHI',
 'BIIB',
 'BK',
 'BLK',
 'BLL',
 'BMY',
 'BSX',
 'BWA',
 'BXP',
 'C',
 'CA',
 'CAG',
 'CAH',
 'CAT',
 'CB',
 'CBG',
 'CBS',
 'CCI',
 'CCL',
 'CELG',
 'CERN',
 'CF',
 'CFG',
 'CHD',
 'CHK',
 'CHRW',
 'CHTR',
 'CI',
 'CINF',
 'CL',
 'CLX',
 'CMA',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMS',
 'CNC',
 'CNP',
 'COF',
 'COG',
 'COH',
 'COL',
 'COO',
 'COP',
 'COST',
 'COTY',
 'CPB',
 'CRM',
 'CSCO',
 'CSRA',
 'CSX',
 'CTAS',
 'CTL',
 'CTSH',
 'CTXS',
 'CVS',
 'CVX',
 'CXO',
 'D',
 'DAL',
 'DD',
 'DE',
 'DFS',
 'DG',
 'DGX',
 'DHI',
 'DHR',
 'DIS',
 'DISCA',
 'DISCK',
 'DLPH',
 'DLR',
 'DLTR',
 'DNB',
 'DOV',
 'DOW',
 'DPS',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'EA',
 'EBAY',
 'ECL',
 'ED',
 'EFX',
 'EIX',
 'EL',
 'EMN',
 'EMR',
 'ENDP',
 'EOG',
 'EQIX',
 'EQR',
 'EQT',
 'ES',
 'ESRX',
 'ESS',
 'ETFC',
 'ETN',
 'ETR',
 'EVHC',
 'EW',
 'EXC',
 'EXPD',
 'EXPE',
 'EXR',
 'F',
 'FAST',
 'FB',
 'FBHS',
 'FCX',
 'FDX',
 'FE',
 'FFIV',
 'FIS',
 'FISV',
 'FITB',
 'FL',
 'FLIR',
 'FLR',
 'FLS',
 'FMC',
 'FOX',
 'FOXA',
 'FRT',
 'FSLR',
 'FTI',
 'FTR',
 'FTV',
 'GD',
 'GE',
 'GGP',
 'GILD',
 'GIS',
 'GLW',
 'GM',
 'GOOG',
 'GOOGL',
 'GPC',
 'GPN',
 'GPS',
 'GRMN',
 'GS',
 'GT',
 'GWW',
 'HAL',
 'HAR',
 'HAS',
 'HBAN',
 'HBI',
 'HCA',
 'HCN',
 'HCP',
 'HD',
 'HES',
 'HIG',
 'HOG',
 'HOLX',
 'HON',
 'HP',
 'HPE',
 'HPQ',
 'HRB',
 'HRL',
 'HRS',
 'HSIC',
 'HST',
 'HSY',
 'HUM',
 'IBM',
 'ICE',
 'IDXX',
 'IFF',
 'ILMN',
 'INTC',
 'INTU',
 'IP',
 'IPG',
 'IR',
 'IRM',
 'ISRG',
 'ITW',
 'IVZ',
 'JBHT',
 'JCI',
 'JEC',
 'JNJ',
 'JNPR',
 'JPM',
 'JWN',
 'K',
 'KEY',
 'KHC',
 'KIM',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KO',
 'KORS',
 'KR',
 'KSS',
 'KSU',
 'L',
 'LB',
 'LEG',
 'LEN',
 'LH',
 'LKQ',
 'LLL',
 'LLTC',
 'LLY',
 'LMT',
 'LNC',
 'LNT',
 'LOW',
 'LRCX',
 'LUK',
 'LUV',
 'LVLT',
 'LYB',
 'M',
 'MA',
 'MAA',
 'MAC',
 'MAR',
 'MAS',
 'MAT',
 'MCD',
 'MCHP',
 'MCK',
 'MCO',
 'MDLZ',
 'MDT',
 'MET',
 'MHK',
 'MJN',
 'MKC',
 'MLM',
 'MMC',
 'MMM',
 'MNK',
 'MNST',
 'MO',
 'MON',
 'MOS',
 'MPC',
 'MRK',
 'MRO',
 'MSFT',
 'MSI',
 'MTB',
 'MTD',
 'MU',
 'MUR',
 'MYL',
 'NAVI',
 'NBL',
 'NDAQ',
 'NEE',
 'NEM',
 'NFLX',
 'NFX',
 'NI',
 'NKE',
 'NLSN',
 'NOC',
 'NOV',
 'NRG',
 'NSC',
 'NTAP',
 'NTRS',
 'NUE',
 'NVDA',
 'NWL',
 'NWS',
 'NWSA',
 'O',
 'OKE',
 'OMC',
 'ORCL',
 'ORLY',
 'OXY',
 'PAYX',
 'PBCT',
 'PBI',
 'PCAR',
 'PCG',
 'PCLN',
 'PDCO',
 'PEG',
 'PEP',
 'PFE',
 'PFG',
 'PG',
 'PGR',
 'PH',
 'PHM',
 'PKI',
 'PLD',
 'PM',
 'PNC',
 'PNR',
 'PNW',
 'PPG',
 'PPL',
 'PRGO',
 'PRU',
 'PSA',
 'PSX',
 'PVH',
 'PWR',
 'PX',
 'PXD',
 'PYPL',
 'QCOM',
 'QRVO',
 'R',
 'RAI',
 'RCL',
 'REGN',
 'RF',
 'RHI',
 'RHT',
 'RIG',
 'RL',
 'ROK',
 'ROP',
 'ROST',
 'RRC',
 'RSG',
 'RTN',
 'SBUX',
 'SCG',
 'SCHW',
 'SE',
 'SEE',
 'SHW',
 'SIG',
 'SJM',
 'SLB',
 'SLG',
 'SNA',
 'SNI',
 'SO',
 'SPG',
 'SPGI',
 'SPLS',
 'SRCL',
 'SRE',
 'STI',
 'STT',
 'STX',
 'STZ',
 'SWK',
 'SWKS',
 'SWN',
 'SYF',
 'SYK',
 'SYMC',
 'SYY',
 'T',
 'TAP',
 'TDC',
 'TDG',
 'TEL',
 'TGNA',
 'TGT',
 'TIF',
 'TJX',
 'TMK',
 'TMO',
 'TRIP',
 'TROW',
 'TRV',
 'TSCO',
 'TSN',
 'TSO',
 'TSS',
 'TWX',
 'TXN',
 'TXT',
 'UAA',
 'UAL',
 'UDR',
 'UHS',
 'ULTA',
 'UNH',
 'UNM',
 'UNP',
 'UPS',
 'URBN',
 'URI',
 'USB',
 'UTX',
 'V',
 'VAR',
 'VFC',
 'VIAB',
 'VLO',
 'VMC',
 'VNO',
 'VRSK',
 'VRSN',
 'VRTX',
 'VTR',
 'VZ',
 'WAT',
 'WBA',
 'WDC',
 'WEC',
 'WFC',
 'WFM',
 'WHR',
 'WLTW',
 'WM',
 'WMB',
 'WMT',
 'WRK',
 'WU',
 'WY',
 'WYN',
 'WYNN',
 'XEC',
 'XEL',
 'XL',
 'XLNX',
 'XOM',
 'XRAY',
 'XRX',
 'XYL',
 'YHOO',
 'YUM',
 'ZBH',
 'ZION',
 'ZTS'}

## Task

The user might be interested in finding the trends of the price for a specific stock. For example, they want to find the trends of price of XYL over time. So, this task is a discover task and the target is to find the trends.

In [10]:
# Find all XYL data
XYL = NYSE_price.loc[NYSE_price["symbol"] == "XYL"]
XYL

,date,symbol,open,close,low,high,volume
354806,2013-01-02,XYL,27.629999,27.500000,27.420000,27.990000,927300.0
355289,2013-01-03,XYL,27.500000,27.410000,27.240000,27.790001,610800.0
355772,2013-01-04,XYL,27.510000,27.370001,27.250000,27.639999,563400.0
356255,2013-01-07,XYL,27.190001,27.010000,26.930000,27.320000,481300.0
356738,2013-01-08,XYL,26.930000,26.680000,26.389999,26.940001,1084500.0
357221,2013-01-09,XYL,26.820000,27.100000,26.760000,27.139999,985500.0
357704,2013-01-10,XYL,27.340000,27.480000,27.120001,27.549999,842000.0
358187,2013-01-11,XYL,27.580000,27.180000,27.090000,27.600000,353400.0
358670,2013-01-14,XYL,27.090000,27.209999,26.750000,27.240000,417400.0
359153,2013-01-15,XYL,27.100000,27.129999,26.730000,27.160000,734400.0
359636,2013-01-16,XYL,27.030001,26.950001,26.650000,27.120001,431800.0
360119,2013-01-17,XYL,27.059999,27.420000,26.830000,27.469999,653400.0
360602,2013-01-18,XYL,27.549999,27.510000,27.139999,27.549999,711400.0
361085,2013-01-22,XYL,27.650000,27.680000,27.340000,27.680000,1457900.0
361568,2013-01-23,XYL,27.620001,27.900000,27.580000,27.920000,977400.0
362051,2013-01-24,XYL,27.860001,27.980000,27.799999,28.260000,1095100.0
362534,2013-01-25,XYL,28.090000,27.700001,27.559999,28.139999,831400.0
363017,2013-01-28,XYL,27.760000,27.920000,27.549999,28.000000,874100.0
363500,2013-01-29,XYL,27.879999,27.969999,27.809999,28.010000,1000700.0
363983,2013-01-30,XYL,27.950001,27.940001,27.900000,28.160000,811100.0
364466,2013-01-31,XYL,27.930000,27.930000,27.889999,28.010000,922700.0
364949,2013-02-01,XYL,28.000000,28.010000,27.910000,28.309999,1239100.0
365433,2013-02-04,XYL,27.870001,27.549999,27.500000,27.900000,914100.0
365917,2013-02-05,XYL,27.730000,27.770000,27.650000,27.990000,695300.0
366401,2013-02-06,XYL,27.610001,27.850000,27.540001,28.030001,1350700.0
366885,2013-02-07,XYL,28.030001,26.910000,26.840000,28.030001,1576400.0
367369,2013-02-08,XYL,27.010000,27.090000,27.010000,27.639999,1206300.0
367853,2013-02-11,XYL,27.110001,27.459999,27.020000,27.530001,875100.0
368337,2013-02-12,XYL,27.520000,27.950001,27.480000,28.100000,905000.0
368821,2013-02-13,XYL,28.000000,28.260000,27.940001,28.370001,622300.0
...,...,...,...,...,...,...,...
836756,2016-11-17,XYL,54.730000,54.009998,53.990002,54.990002,1453800.0
837256,2016-11-18,XYL,53.889999,53.290001,53.090000,53.959999,1517000.0
837756,2016-11-21,XYL,53.529999,53.459999,53.060001,53.700001,895700.0
838256,2016-11-22,XYL,53.490002,52.919998,52.919998,53.639999,1540200.0
838756,2016-11-23,XYL,53.000000,52.860001,52.680000,53.020000,1926000.0
839256,2016-11-25,XYL,52.950001,52.919998,52.590000,52.970001,1023400.0
839756,2016-11-28,XYL,52.369999,51.639999,51.599998,52.689999,1901500.0
840256,2016-11-29,XYL,51.490002,51.340000,50.779999,51.840000,1634200.0
840756,2016-11-30,XYL,51.869999,51.580002,51.200001,52.049999,1520800.0
841256,2016-12-01,XYL,51.900002,51.810001,51.490002,52.049999,1734000.0
841756,2016-12-02,XYL,51.900002,51.799999,51.450001,51.990002,912600.0
842256,2016-12-05,XYL,52.110001,51.720001,51.619999,52.220001,1212200.0
842756,2016-12-06,XYL,51.770000,52.169998,51.599998,52.180000,1474000.0
843256,2016-12-07,XYL,52.200001,52.060001,51.459999,52.400002,1982000.0
843756,2016-12-08,XYL,52.130001,51.889999,51.400002,52.290001,1317500.0
844256,2016-12-09,XYL,51.849998,51.480000,51.119999,51.849998,814100.0
844756,2016-12-12,XYL,51.410000,50.990002,50.910000,51.529999,1063200.0
845256,2016-12-13,XYL,51.060001,50.990002,50.500000,51.230000,969000.0
845756,2016-12-14,XYL,50.939999,50.570000,50.410000,51.480000,1095500.0
846256,2016-12-15,XYL,50.400002,50.139999,50.090000,51.020000,1516600.0
846756,2016-12-16,XYL,50.160000,50.099998,49.919998,50.790001,2503900.0
847256,2016-12-19,XYL,50.090000,50.759998,49.880001,50.810001,1081100.0
847756,2016-12-20,XYL,50.869999,50.919998,50.549999,51.060001,953500.0
848256,2016-12-21,XYL,50.849998,50.830002,50.660000,51.139999,1018300.0
848756,2016-12-22,XYL,51.000000,51.130001,50.810001,51.230000,1003000.0
849256,2016-12-23,XYL,51.080002,51.009998,50.840000,51.180000,539500.0
849756,2016-12-27,XYL,51.000000,50.860001,50.669998,51.220001,466600.0
850256,2016-12-28,XYL,50.980000,49.939999,49.910000,51.150002,740100.0
850756,2016-12-29,XYL,50.029999,49.770000,49.680000,50.220001,626200.0
851256,2016-12-30,XYL,49.980000,49.520000,49.360001,50.000000,646200.0

In [30]:
date = pd.to_datetime(XYL["date"])
lowest_price = XYL["low"]
highest_price = XYL["high"]
open_price = XYL["open"]
close_price = XYL["close"]

In [34]:
# Draw four lines
trace_low = go.Scatter(x = date, y = lowest_price, name = "lowest price", mode = "markers + lines")
trace_high = go.Scatter(x = date, y = highest_price, name = "highest price",  mode = "markers + lines")
trace_open = go.Scatter(x = date, y = open_price, name = "open price", mode = "markers + lines")
trace_close = go.Scatter(x = date, y = close_price, name = "close price", mode = "markers + lines")

In [35]:
# Subplot and layout
fig_line = tools.make_subplots(rows = 4, cols = 1)
fig_line.append_trace(trace_low, 1, 1)
fig_line.append_trace(trace_high, 2, 1)
fig_line.append_trace(trace_open, 3, 1)
fig_line.append_trace(trace_close, 4, 1)

fig_line["layout"].update(
    title = "Price of XYL over time",
    xaxis1 = dict(title = "Date"),
    yaxis1 = dict(title = "Lowest Price"),
    xaxis2 = dict(title = "Date"),
    yaxis2 = dict(title = "Highest Price"),
    xaxis3 = dict(title = "Date"),
    yaxis3 = dict(title = "Open Price"),
    xaxis4 = dict(title = "Date"),
    yaxis4 = dict(title = "Close Price"),
    autosize = True,
    hovermode = "closest"
)

py.iplot(fig_line, filename = "XYL_chart_1")

This is the format of your plot grid:
[ (1,1) x1,y1 ]
[ (2,1) x2,y2 ]
[ (3,1) x3,y3 ]
[ (4,1) x4,y4 ]

I create a line chart to visualize the  price of XYL stock over time. Line chart is especially suitable for the target and can easily find the trends of the data. But there is a problem of this plot, there is a large position of overlapping between two date time and viewers need to zoom in to see a clearer picture. 

Since I fix the symbol to "XYL", the key of this chart is date. The date are encoded using the position on the x-axis. The lowest,highest, open and close price over time are encoded using the points & lines as the marks and position & color as the channels. Also I use four sublot to visualize the data to avoid overlapping among those lines.

In this plot we can find that from 2013 to 2017, the price of XYL stock increase. And from 2016 to 2017 the price increase dramatically.

I use closest hovering, zoom and drag as the interactivity. Since there is a large position of overlapping on this plot, viewers can only see the general trend of the price. By using those interactivity, this plot enable viewers to zoom in and drag to see the detail of data. Also the closest hovering enable viewers to see the corresponding x value and y value of the data when mouse move on one data point.

In [36]:
# Draw Candlestick chart
trace = go.Candlestick(
    x = date, 
    low = lowest_price,
    high = highest_price,
    open = open_price,
    close = close_price
)

In [38]:
# Layout
layout = go.Layout(
    title = "Lowest and highest price of XYL over time",
    xaxis = dict(title = "Date"),
    yaxis = dict(title = "Price"),
    autosize = True,
    hovermode = "closest"
)
fig_candlestick = dict(data = [trace], layout = layout)
py.iplot(fig_candlestick, filename = "XYL chart 2")

I create a candlestick plot to visualize the price of XYL stock over time.In this chart the can show open, close, lowest and highest price for each day in one data point. Also it use color as the channel to show the trend of the data. Red color means the price is decreasing. Green color means the price is increasing.The date time are encoded using the position on the x-axis. The price are encoded using the line as the mark and position & color as the channels.

In this plot there is a gap on the price around Aug 2013 and Nov 2013 which indicate the company may undergoing a hard time.

I use the default interactivity settings and closest hovering. The cloest hovering enable viewers to check the corresponding price of one specific day. The default setting of candlestick plot enable viewers to select a specific time period which helping them better discover the price over time.